NAME = {{.Name}}
OUTPUT = {{.Output}}
MODULE = {{.Module}}
IMAGE = {{.Image}}
{{- if .Embed}}
SOURCES = statik/statik.go go.sum $(wildcard *.go)
{{- else}}
SOURCES = go.sum $(wildcard *.go)
{{- end}}
TARGETS ={{range .Targets}} {{.}}{{end}}
DOCKER ?= docker

os = $(word 1, $(subst /, ,$@))
arch = $(word 2, $(subst /, ,$@))

.PHONY: all
all: $(TARGETS)

go.mod:
	go mod init $(MODULE)

go.sum: go.mod
	go get
{{- if .Embed}}

assets:
	mkdir assets

assets/image.tar.gz: assets
	$(DOCKER) save $(IMAGE) | gzip > assets/image.tar.gz

statik/statik.go: assets/image.tar.gz
	go get github.com/rakyll/statik
	statik -Z -src=assets
{{- end}}

$(OUTPUT):
	mkdir $(OUTPUT)

$(TARGETS): $(SOURCES) $(OUTPUT)
	GOOS=$(os) GOARCH=$(arch) go build -o "$(OUTPUT)/$(NAME)-$(os)-$(arch)"
