NAME = {{.Name}}
OUTPUT = {{.Output}}
MODULE = {{.Module}}
IMAGE = {{.Image}}
{{- if .Embed}}
SOURCES = go.sum $(wildcard *.go) image.tar.gz
{{- else}}
SOURCES = go.sum $(wildcard *.go)
{{- end}}
TARGETS ={{range .Targets}} {{.}}{{end}}
DOCKER ?= docker

os = $(word 1, $(subst /, ,$@))
arch = $(word 2, $(subst /, ,$@))

.PHONY: all
all: $(TARGETS)

go.mod:
	go mod init $(MODULE)

go.sum: go.mod
	go get

image.tar.gz:
	$(DOCKER) save $(IMAGE) | gzip > image.tar.gz

$(OUTPUT):
	mkdir $(OUTPUT)

$(TARGETS): $(SOURCES) $(OUTPUT)
	GOOS=$(os) GOARCH=$(arch) go build -o "$(OUTPUT)/$(NAME)-$(os)-$(arch)"
